- name: openrouter/deepseek/deepseek-r1 
  edit_format: diff
  extra_params:
    extra_body:
      provider:
        sort: "price"
        #sort: "throughput"

- name: openrouter/deepseek/deepseek-r1-distill-llama-70b
  edit_format: whole
  extra_params:
    extra_body:
      provider:
        sort: "throughput"
        # Only use these providers, in this order
        #order: ["Anthropic", "Together"]
        # Don't fall back to other providers
        #allow_fallbacks: false
        # Skip providers that may train on inputs
        #data_collection: "deny"
        # Only use providers supporting all parameters
        #require_parameters: true


- name: openrouter/google/gemini-2.0-flash-001
  edit_format: diff
  extra_params:
    num_ctx: 1000000
    extra_body:
      provider:
        sort: "price"
        #sort: "throughput"
