- name: gemini/gemini-2.0-flash-exp
  edit_format: whole
  extra_params:
    temperature: 1.2
    top_p: 0.9

#- name: deepseek/deepseek-chat
  #edit_format: diff
  #extra_params:
    #temperature: 1.0
    #top_p: 0.9
